.travis.yml
README.md
build.properties.dist
build.xml
composer.json
composer.lock
phpcs-ruleset.xml.dist
scripts/drupal/update-scaffold
web/.eslintrc
web/.htaccess
web/sites/default/default.services.yml
web/sites/default/default.settings.php

https://webgate.ec.europa.eu/CITnet/jira/browse/ISAICP-2161

Isaicp 2161

---

build.xml
composer.json
composer.lock
scripts/composer/post-install.sh

https://webgate.ec.europa.eu/CITnet/jira/browse/ISAICP-2303

ISAICP-2303

---

src/Phing/SetVirtuosoSparqlPermissions.php

Fix Virtuoso privileges issue

---

build.xml
resources/continuousphp/odbc.ini
resources/virtuoso/odbc.ini

https://webgate.ec.europa.eu/CITnet/jira/browse/ISAICP-2310

Isaicp 2310

---

composer.json
composer.lock

https://webgate.ec.europa.eu/CITnet/jira/browse/ISAICP-2386

Isaicp 2386

---

composer.lock
web/modules/custom/custom_page/config/install/core.entity_view_display.node.custom_page.default.yml
web/modules/custom/custom_page/config/install/field.field.node.custom_page.og_group_ref.yml

New PR to make the UAT possible - you can now see which collection a custom page belongs to.

Isaicp 2237

---

composer.json
composer.lock
web/modules/custom/asset_distribution/src/Plugin/Field/FieldWidget/FileSizeCalculatorWidget.php
web/modules/custom/asset_distribution/src/Plugin/Field/FieldWidget/UrlFileSynchronizerWidget.php

Amitai just merged the OG branch that we were tracking and deleted it. This means that we'll have to update composer.json to revert to the main branch of og or our builds will start failing.

Revert to main branch of OG

---

composer.lock
tests/features/authentication.feature
tests/features/dashboard.feature
web/modules/custom/dashboard/dashboard.info.yml
web/modules/custom/dashboard/dashboard.links.menu.yml
web/modules/custom/dashboard/dashboard.permissions.yml
web/modules/custom/dashboard/dashboard.routing.yml
web/modules/custom/dashboard/src/Controller/DashboardController.php
web/profiles/joinup/config/install/user.role.authenticated.yml
web/profiles/joinup/joinup.info.yml

https://webgate.ec.europa.eu/CITnet/jira/browse/ISAICP-2494

Isaicp 2494

---

web/modules/custom/collection/config/install/core.entity_view_display.rdf_entity.collection.view_mode_tile.yml
web/modules/custom/joinup_news/config/install/core.entity_view_display.node.news.view_mode_tile.yml
web/modules/custom/joinup_news/config/install/field.field.node.news.og_group_ref.yml
web/modules/custom/solution/config/install/core.entity_view_display.rdf_entity.solution.view_mode_tile.yml

This was developed along with me and the results are passed. This ticket is not necessarily passed and the ticket does not go through to QA and UAT yet

Issue #ISAICP-2572: Tiles - link to content.

---

composer.lock

Issue #ISAICP-2619: update Drupal core to 8.1.6

---

web/modules/custom/collection/src/Form/JoinCollectionForm.php
web/modules/custom/collection/src/Form/LeaveCollectionConfirmForm.php
web/profiles/joinup/src/Plugin/Block/AddContentBlock.php

ISAICP-2267: Provide cache tags workaround.

---

tests/features/asset_release/add_asset_release.feature

ISAICP-2595: Change heading to match the test.

---

composer.lock

Issue #ISAICP-2632: SA-CORE-2016-003

---

web/modules/custom/collection/collection.module
web/modules/custom/solution/solution.module
web/profiles/joinup/joinup.behat.inc

Isaicp 2663 dev

---

tests/features/asset_release/add_asset_release.feature

ISAICP-2421: Provide debug information for UAT.

---

web/themes/joinup/templates/parts/header.html.twig

ISAICP-2680: Fix joinup logo link

---

web/profiles/joinup/config/install/block.block.joinup_theme_joincollectionblock.yml
web/themes/joinup/joinup_theme.theme
web/themes/joinup/prototype/_layouts/collections.html
web/themes/joinup/templates/parts/block--add-content-block.html.twig
web/themes/joinup/templates/parts/featured--collection.html.twig

ISAICP-2678: Fix elements alignment in the featured header

---

tests/features/joinup_discussion/api.feature
web/modules/custom/joinup_core/config/install/field.storage.node.field_topic.yml
web/modules/custom/joinup_discussion/config/install/core.base_field_override.node.discussion.promote.yml
web/modules/custom/joinup_discussion/config/install/core.base_field_override.node.discussion.status.yml
web/modules/custom/joinup_discussion/config/install/core.entity_view_display.node.discussion.default.yml
web/modules/custom/joinup_discussion/config/install/field.field.node.discussion.field_discussion_active.yml
web/modules/custom/joinup_discussion/config/install/field.field.node.discussion.field_discussion_content.yml
web/modules/custom/joinup_discussion/config/install/field.field.node.discussion.field_topic.yml
web/modules/custom/joinup_discussion/config/install/field.field.node.discussion.og_audience.yml
web/modules/custom/joinup_discussion/config/install/field.storage.node.field_discussion_active.yml
web/modules/custom/joinup_discussion/config/install/field.storage.node.field_discussion_content.yml
web/modules/custom/joinup_discussion/config/install/node.type.discussion.yml
web/modules/custom/joinup_discussion/joinup_discussion.info.yml
web/modules/custom/joinup_discussion/joinup_discussion.module
web/profiles/joinup/joinup.info.yml

Isaicp 2254

---

web/modules/custom/asset_distribution/asset_distribution.module

ISAICP-2749: Fix lack of checking for empty value.

---

build.properties

Fix PHPCS exclude directories

---

.gitignore

ISAICP-2786: Git ignore .sass-cache. Followup of ISAICP-2741.

---

tests/features/asset_distribution/add_asset_distribution.feature
web/modules/custom/asset_distribution/config/install/field.field.rdf_entity.asset_distribution.field_ad_licence.yml

ISAICP-2672 adding description to the distribution license field

---

build.xml
web/modules/custom/rdf_entity/rdf_entity.drush.inc

ISAICP-2708: Add a purge RDF content target for UAT environment

---

README.md
web/themes/joinup/README.md

Isaicp 2740

---

README.md
web/modules/custom/rdf_entity/README.md

Improve READMEs

---

web/modules/custom/solution/solution.module

There is a new update for Coder, this will fail on this line. Let's fix it already so we don't slow down development.

Fix missing type hint.

---

composer.json
composer.lock

See https://webgate.ec.europa.eu/CITnet/jira/browse/ISAICP-3079

Composer 1.3.0

---

tests/features/collection/collection.moderation.feature
tests/features/joinup_news/news_moderation.feature
web/modules/custom/custom_page/config/install/node.type.custom_page.yml
web/modules/custom/joinup_document/config/install/node.type.document.yml
web/modules/custom/joinup_event/config/install/node.type.event.yml
web/modules/custom/joinup_news/config/install/node.type.news.yml

Isaicp 2777 part 2

---

tests/features/solution/related_solution.feature

Provide the test functionality for relating a solution to your solution.
I restructured the related_solution.feature for this. I did the following:
- Provided test owner and contact information entities.
- Provided all mandatory fields for the solutions required for the test.
- Extended the test so that there is a scenario for the facilitator to relate a solution to his solution.

ISAICP-2940: Relate solutions.

---

composer.json
composer.lock

Relevant issues:
- https://www.drupal.org/node/2864379
- https://www.drupal.org/node/2864349

Hotfix: Remove composer dependency on og_ui

---

web/modules/custom/rdf_entity/src/Database/Driver/sparql/Connection.php
web/modules/custom/rdf_entity/src/Exception/SparqlQueryException.php
web/modules/custom/rdf_entity/tests/src/Kernel/RdfQueryExceptionTest.php

database fails to execute a query.

ISAICP-3260: Sparql query exception

---

web/modules/custom/rdf_entity/README.md

Copy&paste didn't work as it was not visible that these are 2 commands.

Minor update in documentation

---

web/themes/joinup/prototype/html-prototype-sandbox/solution-discussion-disabled.html
web/themes/joinup/prototype/html-prototype-sandbox/solution-discussion-login.html
web/themes/joinup/prototype/html-prototype-sandbox/solution-discussion-open.html
web/themes/joinup/prototype/sass/components/_alert.sass

Merge ISAICP-3281 into develop.

ISAICP-3281: Fix error message for files

---

web/themes/joinup/prototype/html-prototype-sandbox/partials/featured--large.mustache
web/themes/joinup/prototype/html-prototype-sandbox/partials/filters.mustache
web/themes/joinup/prototype/html-prototype-sandbox/partials/header.mustache
web/themes/joinup/prototype/sass/base/_input.sass
web/themes/joinup/prototype/sass/components/_search-bar.sass
web/themes/joinup/templates/parts/featured--anonymous.html.twig
web/themes/joinup/templates/parts/header.html.twig

ISAICP-3365: search bar inputs colour fix in drupal and prototype: html/sass/tpl

---

web/modules/custom/asset_release/templates/asset-release-releases-download.html.twig
web/themes/joinup/joinup_theme.theme
web/themes/joinup/prototype/html-prototype-sandbox/solution-discussion-disabled.html
web/themes/joinup/prototype/html-prototype-sandbox/solution-discussion-login.html
web/themes/joinup/prototype/html-prototype-sandbox/solution-discussion-open.html
web/themes/joinup/prototype/sass/components/_action-link.sass
web/themes/joinup/templates/rdf_entity/rdf-entity--asset-distribution--compact.html.twig

Merge ISAICP-2783 into develop

ISAICP-2783: Fix release download page

---

web/themes/joinup/prototype/sass/_drupal-hacks.sass
web/themes/joinup/prototype/sass/_mdl-hacks.sass

ISAICP-3228: double sidebar fix

---

web/themes/joinup/prototype/sass/_mdl-hacks.sass

ISAICP-3283: prefix hiding: sass

---

web/themes/joinup/joinup_theme.theme
web/themes/joinup/prototype/sass/components/_button.sass
web/themes/joinup/templates/block/block--local-actions-block.html.twig
web/themes/joinup/templates/navigation/menu-local-action.html.twig

Merge ISAICP-2892 into develop

ISAICP-2892: Fix local action buttons

---

web/modules/custom/asset_distribution/src/DownloadEventStorageSchema.php
web/modules/custom/asset_distribution/src/Entity/DownloadEvent.php
web/modules/custom/asset_distribution/src/Plugin/Validation/Constraint/DownloadEvent.php
web/modules/custom/asset_distribution/src/Plugin/Validation/Constraint/DownloadEventValidator.php

ISAICP-2810: Create a backend entity for storing download log entries.

---

web/themes/joinup/templates/content/node--document--listing-item.html.twig

Merge ISAICP-3438 into develop

ISAICP-3438: Fix download button on documents tile

---

web/themes/joinup/joinup_theme.theme
web/themes/joinup/prototype/sass/components/_listing.sass
web/themes/joinup/templates/user/user--user--listing-item.html.twig

Merge ISAICP-3449 into develop

ISAICP-3449: Style members collection page

---

web/modules/custom/joinup_event/config/install/core.entity_form_display.node.event.default.yml
web/modules/custom/joinup_news/config/install/core.entity_form_display.node.news.default.yml
web/themes/joinup/prototype/sass/components/_form-table.sass

Merge ISAICP-3358 into develop

ISAICP-3358: Reorder and style mulifile field

---

web/themes/joinup/js/script.js

The changes not related to the global Drupal check are coming from [prettier](https://github.com/prettier/prettier). Please tell me if I am to revert them.

Double-check the presence of global Drupal - noissue

---

web/modules/custom/joinup_discussion/config/install/core.entity_view_display.node.discussion.view_mode_tile.yml
web/modules/custom/joinup_news/config/install/core.entity_view_display.node.news.view_mode_tile.yml
web/themes/joinup/prototype/sass/components/_listing.sass

ISAICP-3362: Style listing tags

---

web/themes/joinup/prototype/sass/components/_form.sass

Merge develop into ISAICP-3488

ISAICP-3488: Fix select element

---

web/themes/joinup/joinup_theme.theme
web/themes/joinup/templates/layout/page.html.twig

Merge develop into ISAICP-3553

ISAICP-3553: Fix add solution page

---

web/themes/joinup/prototype/sass/_drupal-hacks.sass
web/themes/joinup/prototype/sass/components/_button.sass

Merge ISAICP-3489 into develop

ISAICP-3489: Style button in modal

---

web/themes/joinup/js/form.js

Merge ISAICP-3470 into develop

ISAICP-3470: Restore focus on checkboxes

---

web/themes/joinup/prototype/sass/base/_input.sass
web/themes/joinup/prototype/sass/components/_button.sass

Merge ISAICP-3484 into develop

ISAICP-3484: Style confirmation page

---

tests/features/solution/related_solution.feature
web/modules/custom/joinup_communities/trr/trr.module
web/modules/custom/solution/solution.module

ISAICP-3380: Add access check to related solutions + regression

---

composer.json
composer.lock

See https://www.drupal.org/node/2892809 for details.

3655: New version of the pathauto patch

---

composer.lock
tests/behat.yml.dist
tests/features/site_menus.feature
tests/src/Traits/TraversingTrait.php
web/profiles/joinup/joinup.behat.inc
web/profiles/joinup/joinup.profile

Some of them where already reverted in https://github.com/ec-europa/joinup-dev/pull/760

Isaicp 3661: Revert wrong merge that reverted many PRs.

---

composer.json
composer.lock

See https://www.drupal.org/node/2892809

Remove patch #2892809

---

composer.json
composer.lock

See https://www.drupal.org/node/2888903

Remove #2888903 patch

---

tests/features/content_overview.feature
tests/features/homepage.feature
web/modules/custom/joinup_core/joinup_core.links.menu.yml
web/profiles/joinup/config/install/views.view.content_overview.yml

Small correction which was not mentioned in the ticket.

ISAICP-3788: string update

---

composer.json
composer.lock

Ref. https://github.com/Behat/Behat/issues/1076

Temporarily lock Behat until a bug that affects us is fixed.

---

web/themes/joinup/prototype/sass/components/_timeline.sass
web/themes/joinup/templates/rdf_entity/rdf-entity--asset-release--compact.html.twig

Isaicp 3868 develop

---

tests/src/Traits/ContextualLinksTrait.php
web/themes/joinup/prototype/sass/_drupal-hacks.sass

Isaicp 3893 develop

---

web/themes/joinup/templates/content/node--event--listing-item.html.twig

ISAICP-3882: Add event placeholder

---

web/themes/joinup/prototype/sass/components/_icon.sass
web/themes/joinup/templates/user/user--user--listing-item.html.twig

ISAICP-3886: Add user icon in user tiles

---

tests/features/asset_distribution/track_download.feature
tests/features/joinup_search/search.feature
tests/features/solution/homepage.feature
web/modules/custom/asset_release/config/install/core.entity_view_display.rdf_entity.asset_release.view_mode_featured.yml
web/modules/custom/asset_release/config/install/core.entity_view_display.rdf_entity.asset_release.view_mode_tile.yml
web/themes/joinup/templates/rdf_entity/rdf-entity--asset-release--listing-item.html.twig

Isaicp 3887 develop

---

web/themes/joinup/joinup_theme.theme
web/themes/joinup/prototype/sass/components/_listing.sass
web/themes/joinup/templates/rdf_entity/rdf-entity--asset-distribution--listing-item.html.twig

Same as #855 but targeting `develop`.

ISAICP-3883: Changes in distribution tile

---

tests/features/asset_distribution/track_download.feature
web/modules/custom/asset_distribution/src/Form/AnonymousDownloadForm.php
web/themes/joinup/prototype/sass/_drupal-hacks.sass
web/themes/joinup/prototype/sass/components/_button.sass

Cherry picking commits only for ISAICP-3890 issue.
This is assuming that ISAICP-3834 is already available, because previously #899 and #880 were merging changes about the global restyling of the modal on which these changes here are dependent on.

ISAICP-3890

---

composer.json
composer.lock

See https://www.drupal.org/node/2914083

Patch #2914083 has been committed

---

web/modules/custom/joinup_migrate/joinup_migrate.post_update.php

This probably got enabled manually during initial deployment.

ISAICP-4033: Disable the update module on production

---

composer.json
composer.lock

non-existing uuid data attr on images in the wysiwyg editor.

Bug #ISAICP-4158: Update patch: Fix fatal error when using an

---

composer.json
composer.lock
resources/patch/drupal-driver-165.patch

There was a hotfix merged in master that wasn't yet merged back into the develop. This PR is merging this change so the tests can run before this is merged into the develop and master branches.

Develop pre release

---

composer.json
composer.lock

We can no longer justify the high maintenance cost of keeping this dependency.

ISAICP-4318: Remove dependency on Drupal Console.

---

tests/features/community_content/notification.post_moderated.discussion.feature
tests/features/joinup_discussion/discussion.subscribe.feature
web/modules/custom/joinup_notification/config/install/joinup_notification.notifications.community_content.yml
web/modules/custom/joinup_notification/joinup_notification.behat.inc

The commit includes a test as well.

ISAICP-4426: Send discussion creation notifications also to the moderators

---

composer.json
composer.lock
tests/behat.yml.dist
tests/features/bootstrap/FeatureContext.php
tests/features/collection/collection.member_administration.feature
tests/features/collection/collection.member_overview_filtering.feature
tests/features/solution/solution.member_overview.feature
tests/features/solution/solution.member_overview_filtering.feature
tests/src/HtmlManipulator.php
web/modules/custom/collection/collection.module
web/modules/custom/joinup_user/config/install/user.role.moderator.yml
web/profiles/joinup/config/install/views.view.og_members_overview.yml
web/profiles/joinup/joinup.behat.inc
web/profiles/joinup/joinup.info.yml
web/profiles/joinup/joinup.permissions.yml
web/profiles/joinup/joinup.profile

By mistake, I merged #1154 in `develop`. Then I reverted the changes. This PR is to be merged into `develop` after UAT.

ISAICP-4422: Alphabetical order disruption in members of a collection

---

composer.json
composer.lock

We were affected by a critical bug but this is now fixed.

ISAICP-4459: Unlock Composer

---

README.md

Mention the PHP 7.1 requirement in the readme

---

web/modules/custom/joinup_core/src/JoinupRelationManager.php
web/modules/custom/joinup_core/tests/src/Kernel/JoinupKernelTestBase.php

In ISAICP-4498 I identified some technical debt. Let's add documentation that explains what is wrong and links to the relevant tickets that will pay off the debt.

Document technical debt

---

tests/src/Traits/RdfEntityTrait.php

This has been split off from ISAICP-4498. It cleans a dirty trait.

Clean up the RDF Entity trait

---

tests/features/communities/tallinn/initiative_page.feature
web/modules/custom/joinup_communities/tallinn/tallinn.install

I am reopening this as I accidentally merged it to develop but should have been in UAT first.

Isaicp 4615: query to align in the implementation monitoring of Tallinn Collection

---

tests/features/joinup_federation/import.feature
tests/fixtures/files/valid_adms.rdf
web/modules/custom/joinup_communities/spain_ctt/src/Plugin/pipeline/Pipeline/SpainCttPipeline.php
web/modules/custom/joinup_federation/src/JoinupFederationPipelinePluginBase.php
web/modules/custom/joinup_federation/src/Plugin/pipeline/Step/AdmsSchemaEntityReferenceFieldsTrait.php
web/modules/custom/joinup_federation/src/Plugin/pipeline/Step/BrokenReferences.php
web/modules/custom/joinup_federation/src/Plugin/pipeline/Step/RemoveReferencesToBlacklist.php
web/modules/custom/joinup_federation/src/Plugin/pipeline/Step/UserSelectionFilter.php

This should be reworked to run in batch, if #1275 goes first.

4623: Deal with imported data broken references

---

composer.json
composer.lock

https://github.com/minkphp/MinkSelenium2Driver/pull/286
https://webgate.ec.europa.eu/CITnet/jira/browse/ISAICP-4633

Lock MinkSelenium2Driver to prevent test failures on autocomplete fields

---

build.properties

Update Apache Solr.

---

composer.json
composer.lock

Upstream patch https://www.drupal.org/project/redirect/issues/2985288 should be reviewed too.

4558: Cannot redirect from a private file path

---

web/modules/custom/joinup_user/joinup_user.install
web/modules/custom/joinup_user/joinup_user.post_update.php
web/modules/custom/joinup_video/src/Plugin/Filter/JoinupVideo.php
web/profiles/joinup/config/install/filter.format.content_editor.yml

…iv elements are not duplicated.

ISAICP-4658: Sequence of WYSIWYG input filters.

---

tests/features/comments/add_comment.feature
web/modules/custom/joinup_notification/src/EventSubscriber/NotificationSubscriberBase.php

Reverts ec-europa/joinup-dev#1348

Revert "Isaicp 4716: Fix URL pointing to contact form, on emails."

---

tests/features/comments/add_comment.feature
web/modules/custom/joinup_notification/src/EventSubscriber/NotificationSubscriberBase.php

By mistake I messed up the original PR #1348

Restore 4716

---

composer.json
composer.lock

ISAICP-4077: Apply patch to fix bug causing drush to exit with 0 on update error

---

web/modules/custom/joinup_federation/src/Plugin/pipeline/Step/BrokenReferences.php
web/modules/custom/joinup_federation/src/Plugin/pipeline/Step/JoinupValidation.php
web/modules/custom/joinup_federation/src/Plugin/pipeline/Step/ThreeWayMerge.php

This reverts commit 911302d04415d0df0351e6273df06ad8590e956f.

ISAICP-4897: Revert increase of the batch items per iteration.

---

composer.json
composer.lock

The recently released updates is causing test failures.

Temporarily lock Facets on the previous release.

---

composer.json
composer.lock
web/modules/custom/custom_page/tests/src/Kernel/CustomPageOgMenuLinksManagerTest.php

A patch we're using has been updated and no longer applies on older
versions.

ISAICP-4966: Update RDF Entity to the latest version.

---

tests/features/collection/collection.member_overview.feature
tests/features/collection/collection.member_overview_filtering.feature
tests/features/solution/solution.member_overview.feature
tests/features/solution/solution.member_overview_filtering.feature
web/profiles/joinup/config/install/views.view.members_overview.yml
web/profiles/joinup/config/install/views.view.og_members_overview.yml
web/profiles/joinup/joinup.profile
web/themes/joinup/joinup_theme.theme

Reverts ec-europa/joinup-dev#1427

Revert "Isaicp 4471: Unify the filters on the members page and expose them"

---

web/modules/custom/joinup_core/joinup_core.post_update.php

Reverts ec-europa/joinup-dev#1485

Revert "ISAICP-3990: Swap the syslog with the dblog."

---

scripts/update_production.sh
scripts/update_uat.sh

See the ticket for other change made to Jenkins build scripts.

5255: Fix UAT failure

---

tests/features/legal/legal_notice.feature
web/modules/custom/legal/joinup_legal.behat.inc
web/modules/custom/legal/joinup_legal.module

~Note that this has been branched-off from ISAICP-5348. That should me merged first in `develop` and then merge `develop` here.~ EDIT: ISAICP-5348 has been merged.

5349: Accept the Legal notice on the contact Joinup support form

---

composer.json
composer.lock
tests/features/eulogin/eulogin.feature
web/modules/custom/eulogin/joinup_eulogin.module
web/modules/custom/eulogin/joinup_eulogin.services.yml
web/modules/custom/eulogin/src/Event/Subscriber/JoinupEuLoginCasEventsSubscriber.php
web/modules/custom/eulogin/src/JoinupEuLoginAuthnameItemList.php
web/modules/custom/joinup_cas_mock_server/joinup_cas_mock_server.services.yml
web/modules/custom/joinup_cas_mock_server/src/EventSubscriber/JoinupCasMockServerSubscriber.php

**WARNING** This is branched off from ISAICP-5419 and should be merged after the other one is merged in the epic.

5485: EU Login: Fix failures when creating new account

---

web/modules/custom/collection/collection.info.yml
web/modules/custom/joinup_discussion/joinup_discussion.info.yml
web/modules/custom/joinup_notification/joinup_notification.info.yml
web/modules/custom/joinup_subscription/joinup_subscription.info.yml
web/modules/custom/solution/solution.info.yml
web/profiles/joinup/joinup.info.yml

These were forgotten during the CMI update.

ISAICP-5605: Update lists of exported config.

---

web/modules/custom/asset_distribution/src/Plugin/Field/FieldFormatter/TrackedHostedFileDownloadFormatter.php
web/themes/joinup/prototype/sass/components/_button.sass
web/themes/joinup/templates/rdf_entity/rdf-entity--asset-distribution--full.html.twig

This reverts commit 2492dca68d6513bd9c4fa653df6327ae80c82b0a.

Revert 'Revert "ISAICP-5470: Style the links on distribution pages"'

---

build.continuousphp.xml
tests/behat-no-selenium-cphp.yml.dist
tests/behat-only-selenium-cphp.yml.dist

ISAICP-5706: Run Behat in parallel

---

build.continuousphp.xml
build.properties

ISAICP-5726: Wait for CPHP services to get up and be ready

---

tests/features/joinup_subscription/my_subscriptions.feature

ISAICP-5830: Test failure affecting CCS epic

---

scripts/update_production.sh
scripts/update_uat.sh

ISAICP-5837: Remove generating missing path aliases from deploy script

---

composer.lock
phpcs-ruleset.xml.dist
web/modules/custom/contact_form/src/EventSubscriber/NotificationSubscriber.php
web/modules/custom/custom_page/src/CustomPageOgMenuLinksManager.php

There was an update for the Coder module which traditionally involves manually fixing some new coding standards violations. Sadly there were none so I have taken the opportunity to remove 2 of the previously omitted sniffs from `phpcs-ruleset.xml` in this PR. At least we have some improvement on the coding standards front now :grin:

ISAICP-5891: Update dependencies

---

composer.json
composer.lock

We have a bunch of module updates which include some of our patches.
I had to lock Password Policy on the last alpha release since 2 of our patches are causing conflicts with the new release. A followup ticket is being created for this.

ISAICP-5970: Update dependencies

---

build.continuousphp.xml
build.converted.xml
build.project.xml
resources/runner/dev.yml
scripts/continuousphp/check_deprecated_code.sh

This is included as a non-blocking test in the CPHP pipeline.

ISAICP-5890: Check contrib code for deprecation warnings

---

config/sync/facets.facet.type.yml
tests/features/joinup_search/search.feature
web/modules/custom/joinup_search/src/Plugin/facets/processor/ContentTypeFixedWidgetOrderProcessor.php

ISAICP-5766: Sort the Content Types facet results according to a predefined order

---

web/themes/joinup/joinup_theme.theme
web/themes/joinup/prototype/scss/app.scss
web/themes/joinup/prototype/scss/components/_glossary.scss
web/themes/joinup/templates/content/node--glossary--full.html.twig

note: if you encounter merge conflicts on the _glossary.scss file, please keep all css rules defined in both branches

ISAICP-6124: Improvement for the Glossary term page.

---

config/sync/field.field.node.event.body.yml
tests/features/community_content/add_community_content.feature
tests/features/joinup_seo/event.feature

ISAICP-5952: No longer display the summary in the event edit form

---

config/sync/field.field.node.news.body.yml
tests/features/community_content/add_community_content.feature
tests/features/joinup_seo/news.feature

ISAICP-5953: The summary should no longer be shown in the news edit form

---

.env.dist
resources/runner/file_system.yml
resources/runner/toolkit.yml

This PR needs CPHP pipeline changes, so the tests are done in the `refs/heads/ISAICP-6185` pipeline. The successful build is [ced88189-a3cc-4fa0-8cd4-4ff1249468f1](https://app.continuousphp.com/git-hub/ec-europa/joinup-dev/build/ced88189-a3cc-4fa0-8cd4-4ff1249468f1).

ISAICP-6185: Private & temp dirs env vars should be absolute or relative to project

---

web/themes/joinup/prototype/package-lock.json
web/themes/joinup/prototype/package.json

ISAICP-6191: fix prototype pollution npm vulnerability yargs dependencies

---

composer.lock

Ref. https://www.drupal.org/sa-core-2021-002

ISAICP-6494: Fix critical security vulnerability SA-CORE-2021-002

---

scripts/solr/restore_solr.sh

This reverts commit b05c8540bcfde95e6f43ef95b157208e5bf4d700.

ISAICP-6567: Revert ISAICP-6544.
