web/profiles/joinup/config/install/user.role.moderator.yml
Until permission override is allowed in OG (just like node_access_strict was being used), the moderator will use the 'administer group' OG permission to have global access to the groups.
=> ISAICP-2524

build.xml
Hello!
We fixed some issues in supervisord configuration of our containers. This also concerns virtuoso. It can now be restarted using supervisor:
```sudo supervisorctl restart virtuoso```
This has also the advantage that the Phing becomes independant of the virtuoso version.
Sorry for the BC break!
=> changed virtuoso restart to supervisorctl

build.migration.xml, web/modules/custom/joinup_migrate/fixture/1.contact.sql, web/modules/custom/joinup_migrate/fixture/1.contact_solution.sql, web/modules/custom/joinup_migrate/fixture/1.owner.sql, web/modules/custom/joinup_migrate/fixture/1.owner_solution.sql, web/modules/custom/joinup_migrate/joinup_migrate.install, web/modules/custom/joinup_migrate/src/Plugin/migrate/source/Solution.php
On a new install I enabled the `joinup_migrate` module. Then, looking into the new tables `d8_contact` and `d8_owner`, I see them both empty. And this is logic because they are both based on view `d8_solution`. And that is a view based on other migrations that were not run yet.
**Solution**: Use different, lightweight, views for `solution` migration.
=> Revert 3234 (views > tables)

src/Phing/SetMysqlAutoincrement.php
Starting with PHP 7, the `mysqli` extension has been replaced with the `pdo_mysql` extension in the default install. Let's support both.
=> Support PDO in addition to MySQLi

build.project.xml
The fix is to swap `redirect-outgoing-email` and `enable-dev-modules` since there is mail being sent while the dev modules are being enabled.
Our improved `redirect-outgoing-email` target has been contributed upstream to the drupal-project fork and merged back down.
=> Builds fail because of mail being sent before it is redirected

composer.json, composer.lock
This updates the distribution to the latest 8.5.2 release of Drupal core.
As part of this update Composer needed to be locked on the previous release, since the latest 1.6.4 release has a critical issue that causes packages to go missing from `composer.lock`, ref: https://github.com/composer/composer/issues/7268.
=> ISAICP-4452: Apply Drupal 8.5.2 security update

web/modules/custom/joinup_core/src/Guard/NodeGuard.php, web/modules/custom/joinup_core/src/JoinupRelationManager.php, web/modules/custom/joinup_core/src/JoinupRelationManagerInterface.php, web/modules/custom/joinup_core/src/ProxyClass/JoinupRelationManager.php
I encountered this method during my work on ISAICP-4498 and it confused my brains. The documentation did not help to unconfuse. So let's fix.
=> Clarify the method that retrieves the parent's eLibrary creation option

web/modules/custom/joinup_community_content/joinup_community_content.module, web/modules/custom/joinup_core/src/JoinupRelationManager.php, web/modules/custom/joinup_core/src/JoinupRelationManagerInterface.php, web/modules/custom/joinup_core/src/ProxyClass/JoinupRelationManager.php
This has been split off from ISAICP-4498. It cleans up the `JoinupRelationManager` service:
* Use strict typing.
* Return type hinting.
* Use plural argument names for array types.
* Use a constant instead of a magic number.
* Small documentation fixes.
* Type hint on the interface rather than the object.
=> Clean up the JoinupRelationManager service

build.project.xml
When I try to execute the `purge-rdf-content` Phing target I get an error:
```
$ ./vendor/bin/phing purge-rdf-content
[Symfony\Component\Console\Exception\CommandNotFoundException]  
Command "rdf-entity-purge" is not defined.                      
Exception trace:
Symfony\Component\Console\Application->find() at /home/pieter/v/joinup/vendor/drush/drush/src/Application.php:234
Drush\Application->bootstrapAndFind() at /home/pieter/v/joinup/vendor/drush/drush/src/Application.php:191
Drush\Application->find() at /home/pieter/v/joinup/vendor/symfony/console/Application.php:229
Symfony\Component\Console\Application->doRun() at /home/pieter/v/joinup/vendor/symfony/console/Application.php:148
Symfony\Component\Console\Application->run() at …
```
=> Remove obsolete Phing target.

web/modules/custom/joinup_federation/src/Plugin/pipeline/Step/DrupalValidation.php
The array did not result in skipping any kind of violations. It was there for the follow up tickets that will handle each case separately. Revert this commit.
This reverts commit c4b9f96974d013fa9ab5334940879b49ae1d7e7b.
=> Revert "ISAICP-4572: Revert extending the whitelisting array.

composer.json, composer.lock
Later versions of the piwik module have an upgrade path to move to the matomo module but this cannot be done automatically as piwik is a dependency of the project.
=> ISAICP-4630: Lock piwik to version 1.2.

build.project.xml, build.properties, build.properties.dist, build.uat.xml, composer.json, composer.lock, scripts/rpmbuild/make_joinup_build_uat.sh, scripts/update_production.sh, web/profiles/joinup/joinup.profile
Contains:
* A new Phing target `create-uat-settings` that builds the `settings.php`, `settings.local.php` and `services.yml` files without needing to run the entire Drupal installation. This is needed because in UAT we want to rebuild those files and not preserve them, as the might have changes during the development process.
* The SPARQL connection namespace can be configured. Stolen from ISAICP-4206.
* The checkpoint Phing targets are not running if the binary `isql` is missed.
* Retuning a non-zero code from `./scripts/update_production.sh`, when the status report is not clean, is temporary disabled as this breaks the Jenkins AND (&&) chained commands, preventing commands chained after this script to not run. This temporary hack will be disabled as soon as ISAICP-4702, ISAICP-4701 and …
=> 4757: Fix UAT

composer.json, composer.lock
The latest version of Composer is throwing warnings:
>Deprecation warning: require.SEMICeu/adms-ap_validator is invalid, it should not contain uppercase characters. Please use semiceu/adms-ap_validator instead. Make sure you fix this as Composer 2.0 will error.
=> Composer dependency names should be in lowercase

build.properties, build.properties.docker, build.solr.xml
The build properties for the Solr server were integrated in the properties for the Solr cores when we provided Docker integration. This made it possible to host each core on a different Solr server. Unfortunately the properties were not applied on all existing Phing targets which broke the Solr integration on local (non-Docker) environments.
=> ISAICP-5091: Restore build properties for Solr cores

tests/features/bootstrap/FeatureContext.php
While reading `FeatureContext` my eye fell on two calls to `sprintf()` with incorrect parameters. I fixed these calls.
=> Correct usage of sprintf() in FeatureContext

web/modules/custom/rdf_schema_field_validation/tests/src/Kernel/RdfSchemaFieldValidationTest.php
When the Simpletest module is enabled a `MissingGroupException` is being thrown for `RdfSchemaFieldValidationTest`.
=> Add missing test group

tests/features/joinup_document/document.moderation.feature, tests/features/joinup_event/event.moderation.feature, tests/src/Context/ScreenshotContext.php, web/modules/custom/asset_distribution/asset_distribution.behat.inc, web/modules/custom/asset_release/asset_release.behat.inc, web/modules/custom/collection/collection.behat.inc, web/modules/custom/contact_form/contact_form.behat.inc, web/modules/custom/contact_information/contact_information.behat.inc, web/modules/custom/custom_page/custom_page.behat.inc, web/modules/custom/joinup_discussion/joinup_discussion.behat.inc, web/modules/custom/joinup_document/joinup_document.behat.inc, web/modules/custom/joinup_event/joinup_event.behat.inc, web/modules/custom/joinup_licence/joinup_licence.behat.inc, web/modules/custom/joinup_news/joinup_news.behat.inc, web/modules/custom/joinup_user/joinup_user.behat.inc, web/modules/custom/owner/owner.behat.inc, web/modules/custom/pipeline/pipeline.behat.inc, web/modules/custom/solution/solution.behat.inc, web/profiles/joinup/joinup.behat.inc
This is flowing out of https://github.com/ec-europa/joinup-dev/pull/1508#discussion_r266019018 in which @idimopoulos remarks that allowing to omit the subject from a step definition is pointless and allows to create user scenarios that are not grammatically correct.
"When am on the homepage" is not correct English :)
I took this out of the previous PR since this practice turned out to be very wide spread and would just confuse the other ticket.
=> Update step definitions to be more grammatically correct

web/profiles/joinup/src/Plugin/Block/RecommendedContentBlock.php
While working on ISAICP-5172 I noticed that the homepage is loading very slowly for moderators due to 100 groups being loaded unnecessarily. This speeds up that page by just loading the entity IDs rather than the full entities.
=> Avoid loading full group entities if not strictly necessary

composer.json, composer.lock
The latest version 8.x-1.4 is suddenly showing a new "All events" facet on all
group overview pages and this is making these pages uncacheable.
See https://www.drupal.org/project/facets/issues/2692027
=> ISAICP-5257: Lock Facets on the previous version.

web/profiles/joinup/joinup.routing.yml
This route definition reappeared, probably due to a botched merge.
=> The legal notice route no longer exists.

web/modules/custom/joinup_user/config/install/field.field.user.user.field_user_photo.yml, web/modules/custom/joinup_user/joinup_user.install, web/modules/custom/joinup_user/joinup_user.post_update.php
I can only make assumptions as to why this happened. However, here are some clues.
The first change regarding this is 
```
--- a/web/modules/custom/joinup_user/config/install/field.field.user.user.field_user_photo.yml
+++ b/web/modules/custom/joinup_user/config/install/field.field.user.user.field_user_photo.yml
@@ -27,7 +27,7 @@ settings:
title_field: false
title_field_required: false
default_image:
-    uuid: 7194c32e-425b-4c2b-9027-056c6b7edc2f
+    uuid: 2e24bbc5-dedf-42b0-85cf-35940274c2f8
alt: ''
title: ''
width: 640
```
The first uuid, `7194c32e-425b-4c2b-9027-056c6b7edc2f` was updated in #bd88a2d8 where Pieter re-exported the configuration due to moving to Drupal core 8.4.x.
Before this change, we had it set as empty.
Another clue, is that when using the production database, there …
=> ISAICP-5332: Reset the user's default image.

composer.json, composer.lock
* There is a new core update that includes one of our patches.
* symfony/css-selector ~2.8 no longer resolves, possibly this is due to Symfony 2 being EOL soon. We do not strictly depend on the 2.x branch for our needs, so I relaxed it as much as possible.
=> ISAICP-5462: Update dependencies.

build.project.xml, config/sync/config_ignore.settings.yml, scripts/update_production.sh, scripts/update_uat.sh, web/modules/custom/joinup_core/joinup_core.install, web/profiles/joinup/joinup.post_update.php
This is built on top of ISAICP-5051 and blocked on that.
=> 5550: Run content operations after new modules are installed via CMI

build.properties
Currently, we use solr 6.6 as all environments are configured for solr 6 and even CPHP is configured for solr 5. 
However, the default URL for apache solr only has links for specific versions of apahce solr 7 and 8.
**Proposed resolution**
Use the archive URL to have access to all versions of solr.
=> Use the default solr url to download solr.

web/modules/custom/joinup_core/src/Plugin/Field/FieldType/CurrentWorkflowState.php, web/modules/custom/joinup_core/src/Plugin/Field/FieldType/CurrentWorkflowStateFieldItemList.php
Fixes the following deprecation warning:
> Automatically creating the first item for computed fields is deprecated in Drupal 8.5.x and will be removed before Drupal 9.0.0. Use \Drupal\Core\TypedData\ComputedItemListTrait instead.
In Drupal 9 all computed fields should provide an initial value when the field is first accessed. Our `CurrentWorkflowState` computed field predates Drupal 8.5 and was not yet doing it. The fix is simple since we do not need to compute an initial value, this is set in the widget. So this PR is simply setting an empty string as the initial value.
=> Depending on the initial computed field value being auto-created is deprecated

composer.json, composer.lock, tests/features/eulogin/anonymous_403_redirect_caching.feature
Upstream PR that needs review, too https://www.drupal.org/project/drupal/issues/2946073
The bug occurs only if there's an enabled module implementing `hook_node_grants()`. We use the `view_unpublished` module implementing this hook.
```
Given users:
| Username | Roles     |
| boss     | moderator |
Given I am logged in as boss
And I go to the "Cache debug collection" collection
When I click the contextual link "Add new page" in the "Left sidebar" region
And I fill in the following:
| Title | A page        |
| Body  | something ... |
And I uncheck the box "Published"
When I press "Save"
Then I should see the success message "Custom page A page has been created."
And I should see the heading "A page"
When I am not logged in
And I go to the "A page" custom page
Then I should see the heading …
```
=> ISAICP-5972: Don't cache the redirect when a node changes its visibility

tests/features/collection/collection.event.feature
The 'current events' and 'past events' change at midnight, and this was causing failures in tests started late at night.
Don't test events scheduled in the next and previous days, so that our devs can continue to burn the midnight oil.
=> ISAICP-6025: Prevent test failures around midnight.

composer.json, composer.lock
Fixes following warning:
> License "EUPL" is not a valid SPDX license identifier, see https://spdx.org/licenses/ if you use an open license.
The lock file has also been regenerated using `composer update --lock` because the hash was invalid due to recent merges. No changes were made to any dependencies.
=> Use the correct SPDX licence identifier

web/modules/custom/asset_release/src/Entity/AssetRelease.php, web/modules/custom/asset_release/src/Entity/AssetReleaseInterface.php, web/modules/custom/collection/collection.module, web/modules/custom/collection/src/Entity/CollectionInterface.php, web/modules/custom/contact_information/contact_information.module, web/modules/custom/contact_information/src/Entity/ContactInformation.php, web/modules/custom/contact_information/src/Entity/ContactInformationInterface.php, web/modules/custom/joinup_community_content/src/Entity/CommunityContentBase.php, web/modules/custom/joinup_community_content/src/Entity/CommunityContentInterface.php, web/modules/custom/joinup_workflow/src/EntityWorkflowStateInterface.php, web/modules/custom/joinup_workflow/src/EntityWorkflowStateTrait.php, web/modules/custom/owner/owner.module, web/modules/custom/owner/src/Entity/Owner.php, web/modules/custom/owner/src/Entity/OwnerInterface.php, web/modules/custom/solution/solution.module, web/modules/custom/solution/src/Entity/Solution.php, web/modules/custom/solution/src/Entity/SolutionInterface.php
Since the affected code was accessing the workflow state directly on the `$solution->field_is_state` field and there was a generous amount of time foreseen for this ticket I have also created a new `EntityWorkflowStateInterface` class which has a method `::getWorkflowState()` and implemented it for all bundles that are using workflow.
=> ISAICP-5984: Solve circular dependency between solution and collection modules

web/modules/custom/joinup_core/joinup_core.post_update.php
In the latest commit of https://github.com/ec-europa/joinup-dev/pull/2209 the last post update was removed since it was released as a hotfix but the very next one had its numbering lowered.
However, that caused it to be an already run update.
Fixing the naming of the latest PR.
=> Fix the naming of the latest post update.

tests/features/pin_in_solution.feature
This makes it more explicit which part of the test is failing, and makes it easy to revert to a good working state in the future.
=> ISAICP-6241: Comment out the randomly failing tests instead of reshuffling the order of tiles

tests/features/asset_release/asset_release.overview.feature
It seems this has already been fixed, so this is just adding test coverage for this use case.
=> ISAICP-5912: Anonymous users should not get linked to draft releases

resources/runner/solr.yml
In commit [2575c422](https://github.com/ec-europa/joinup-dev/commit/2575c42235b646158e621212757e455027720c65) an accidental change was introduced in the configuration that instructs the task runner to create a symlink from the Solr binary to `./vendor/bin/solr` for easy access. After this change the original Solr binary is overwritten with a self-referential symlink, making it impossible to start Solr.
=> Ensure that the Solr binary is not overwritten with a self-referential symlink

tests/src/Context/JoinupCommunityContentContext.php
We are suffering since yesterday from a frequently occurring RFT. It has been solved by @idimopoulos in scope of ISAICP-6139. This PR is cherry-picking the fix from ISAICP-6139 so that this can be merged in develop and unblock us.
=> RFT: publication date is 1 second later than creation date

web/modules/custom/joinup_core/joinup_core.deploy.php
Only happens on an empty database so will not affect production, but let's fix this anyway since it may cause lost time in development.
=> Fix division by zero error in deploy hook

web/themes/joinup/package-lock.json, web/themes/joinup/package.json
Fixes CVE-2021-33502 and CVE-2020-28469.
=> ISAICP-6547: Update NPM dependencies.

composer.lock
=> ISAICP-6554: Update CTools to 3.7.0.

config/sync/views.view.in_the_spotlight.yml, web/themes/ventuno/src/scss/components/_in-the-spotlight-block.scss, web/themes/ventuno/templates/content/node--numbered-listing.html.twig, web/themes/ventuno/ventuno.theme
Adapts the following:
1. Move the title underneath the Topics badges
1. Show the date and content type (note that the date is using a different date format than is used in the design mockups. The UX designer is not aware of a previous decision to consistently use DD/MM/YYYY across the entire website)
1. Hide the result counter so it can be implemented using CSS
=> ISAICP-6650: Backend fixes for the In The Spotlight block

composer.json, composer.lock
This is a retest of the first commit of #2639. This was green last Friday, but all subsequent builds started failing, both on branches that include this patch and that do not.
It was expected that the main develop branch would start failing after the upstream PR https://github.com/openeuropa/oe_webtools/pull/111 was updated, but the first commit in #2639 was supposed to fix this. Initially it appeared to be successful, but as soon as the latest changes from develop were merged in there it started failing, and ever since that moment all builds are failing, both on CPHP and on the new infrastructure.
Here is the green build for this commit, showing that the patch worked the first time it was tested: https://app.continuousphp.com/git-hub/ec-europa/joinup-dev/build/c7082586-e55e-45cd-b620-386b …
=> ISAICP-6722: Retest using previously green commit
